"use client";
import { Check, LoaderCircle } from "lucide-react";
import { httpsCallable } from "firebase/functions";
import { FormEvent, useState } from "react";
import { getFirebaseFunctions } from "@/lib/firebase/client";
import type { LeadAssignee } from "@/repositories/interfaces/lead-repository";

type Settings = { mode: "manual" | "round_robin" | "destination_specialist"; defaultUid?: string; eligibleUids: string[]; destinationOwners: Record<string, string>; firstResponseMinutes: number; autoAssignLeads: boolean };
export function LeadAssignmentSettings({ initial, team }: { initial: Settings; team: LeadAssignee[] }) {
  const [value, setValue] = useState(initial); const [destinations, setDestinations] = useState(Object.entries(initial.destinationOwners).map(([destination, uid]) => `${destination}=${uid}`).join("\n")); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); try { const destinationOwners = Object.fromEntries(destinations.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [destination, uid] = line.split("=").map((part) => part.trim()); if (!destination || !uid) throw new Error(`Use destination=uid for: ${line}`); return [destination.toLowerCase(), uid]; })); await httpsCallable(getFirebaseFunctions(), "updateLeadAssignmentSettings")({ ...value, destinationOwners }); setMessage("Assignment policy saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Settings could not be saved."); } finally { setBusy(false); } }
  return <form className="settings-form" onSubmit={save}>{error && <p className="lead-form-error">{error}</p>}{message && <p className="lead-form-success"><Check/>{message}</p>}<section className="profile-panel"><header><div><span>1</span><div><h2>Assignment policy</h2><p>Control how new inbound leads receive an owner.</p></div></div></header><div className="settings-fields"><label><span>Mode</span><select value={value.mode} onChange={(event) => setValue((current) => ({ ...current, mode: event.target.value as Settings["mode"] }))}><option value="manual">Manual / creator</option><option value="round_robin">Round robin</option><option value="destination_specialist">Destination specialist</option></select></label><label><span>Default owner</span><select value={value.defaultUid || ""} onChange={(event) => setValue((current) => ({ ...current, defaultUid: event.target.value || undefined }))}><option value="">Use creator</option>{team.map((member) => <option value={member.uid} key={member.uid}>{member.displayName}</option>)}</select></label><label><span>First-response SLA (minutes)</span><input type="number" min="5" max="1440" value={value.firstResponseMinutes} onChange={(event) => setValue((current) => ({ ...current, firstResponseMinutes: Number(event.target.value) }))}/></label><label className="settings-check"><input type="checkbox" checked={value.autoAssignLeads} onChange={(event) => setValue((current) => ({ ...current, autoAssignLeads: event.target.checked }))}/><span>Automatically apply this policy to new leads</span></label></div></section><section className="profile-panel"><header><div><span>2</span><div><h2>Eligible team</h2><p>Round robin only selects checked team members.</p></div></div></header><div className="settings-team">{team.map((member) => <label key={member.uid}><input type="checkbox" checked={value.eligibleUids.includes(member.uid)} onChange={(event) => setValue((current) => ({ ...current, eligibleUids: event.target.checked ? [...new Set([...current.eligibleUids, member.uid])] : current.eligibleUids.filter((uid) => uid !== member.uid) }))}/><span><b>{member.displayName}</b><small>{member.role} · {member.uid}</small></span></label>)}</div></section><section className="profile-panel"><header><div><span>3</span><div><h2>Destination specialists</h2><p>One mapping per line, such as japan=user-uid.</p></div></div></header><div className="settings-fields"><label><span>Destination mappings</span><textarea rows={8} value={destinations} onChange={(event) => setDestinations(event.target.value)} placeholder="japan=user-uid&#10;maldives=another-uid"/></label></div></section><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : <Check/>}Save assignment policy</button></form>;
}
