"use client";
import { ArrowRight, LoaderCircle } from "lucide-react";
import { httpsCallable } from "firebase/functions";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { getFirebaseFunctions } from "@/lib/firebase/client";
import type { LeadAssignee } from "@/repositories/interfaces/lead-repository";

export function NewLeadForm({ team, canAssign }: { team: LeadAssignee[]; canAssign: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await httpsCallable(getFirebaseFunctions(), "captureInboundLead")({ source: form.get("source"), fullName: form.get("fullName"), phone: form.get("phone"), email: form.get("email") || undefined, destinations: String(form.get("destinations") || "").split(",").map((item) => item.trim()).filter(Boolean), requirements: form.get("requirements"), priority: form.get("priority"), ...(canAssign && form.get("assignedUid") ? { assignedUid: form.get("assignedUid") } : {}) }); const result = response.data as { leadId: string }; router.push(`/admin/crm/${result.leadId}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Lead could not be created."); setBusy(false); } }
  return <form className="new-lead-form" onSubmit={submit}>{error && <p className="lead-form-error">{error}</p>}<div className="lead-form-grid"><label><span>Traveller name *</span><input required minLength={2} name="fullName"/></label><label><span>Phone *</span><input required minLength={7} name="phone" inputMode="tel"/></label><label><span>Email</span><input type="email" name="email"/></label><label><span>Source</span><select name="source" defaultValue="phone"><option value="phone">Phone</option><option value="walkin">Walk-in</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="social">Social</option></select></label><label><span>Destinations</span><input name="destinations" placeholder="Japan, Singapore"/></label><label><span>Priority</span><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label>{canAssign && <label><span>Owner</span><select name="assignedUid"><option value="">Apply assignment policy</option>{team.map((member) => <option value={member.uid} key={member.uid}>{member.displayName}</option>)}</select></label>}<label className="lead-field-wide"><span>Requirement</span><textarea name="requirements" rows={6} placeholder="Dates, travellers, budget and preferences"/></label></div><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : <ArrowRight/>}Create lead</button></form>;
}
