import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BedDouble, CheckCircle2, MapPin, MessageCircle, ShieldCheck, Sparkles, Star, Utensils } from "lucide-react";
import { getPublicContent } from "@/lib/public-content";
import { whatsappHref } from "@/lib/utils";
export async function generateStaticParams(){return(await getPublicContent()).hotels.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const hotel=(await getPublicContent()).hotels.find((item)=>item.slug===slug);return hotel?{title:hotel.seo.title||hotel.name,description:hotel.seo.description||hotel.summary}:{}}
export default async function HotelDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const{hotels,destinations}=await getPublicContent();const hotel=hotels.find((item)=>item.slug===slug);if(!hotel)notFound();const destination=destinations.find((item)=>item.slug===hotel.destinationSlug);return <div className="hotel-detail"><div className="market-breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/hotels">Hotels</Link><span>/</span><b>{hotel.name}</b></div><section className="hotel-detail-hero"><Image src={hotel.image} alt={hotel.imageAlt} fill priority sizes="100vw"/><div><span>{hotel.priceBand} stay</span><h1>{hotel.name}</h1><p><MapPin/>{hotel.location}{destination?` · ${destination.name}`:""}</p><div>{Array.from({length:Math.round(hotel.starRating)},(_,index)=><Star key={index}/>)}</div></div></section><section className="hotel-detail-layout"><main><span><Sparkles/>TLC curated stay</span><h2>Why consider this hotel</h2><p>{hotel.summary}</p><div className="hotel-detail-facts"><article><BedDouble/><b>Room options</b><span>{hotel.roomTypes.join(" · ")||"Selected for your brief"}</span></article><article><Utensils/><b>Meal plans</b><span>{hotel.mealPlans.join(" · ")||"Confirmed with your quote"}</span></article></div>{hotel.amenities.length>0&&<section><h2>Hotel highlights</h2><div className="hotel-amenities">{hotel.amenities.map((item)=><span key={item}><CheckCircle2/>{item}</span>)}</div></section>}</main><aside><h2>Include this stay in your trip</h2><p>TLC will check the room category, cancellation policy and live price for your travel dates.</p><Link className="button button-gold" href={`/plan-my-trip?hotel=${encodeURIComponent(hotel.name)}`}>Plan with this hotel <ArrowRight/></Link><a href={whatsappHref(`Hi TLC Holidays, I’m interested in ${hotel.name}. Please check it for my dates.`)}><MessageCircle/>Ask on WhatsApp</a><small><ShieldCheck/>No availability or price is assumed until TLC confirms it.</small></aside></section></div>}
