import { ArrowLeft, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, History, Mail, MapPin, MessageCircle, Phone, Sparkles, Tags, UserRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminUser } from "@/lib/auth/session";
import { FirestoreCustomerRepository } from "@/repositories/firebase/firestore-customer-repository";

function formatDate(value?: string) {
  return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "Not available";
}

export default async function CustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireAdminUser("crm:read"); const { id } = await params;
  const repository = new FirestoreCustomerRepository(user.orgId);
  const [customer, travelHistory, events] = await Promise.all([repository.getCustomer(id), repository.listTravelHistory(id), repository.listEvents(id)]);
  if (!customer) notFound();

  return <><Link className="admin-back" href="/admin/customers"><ArrowLeft/>Customer directory</Link><header className="customer-hero"><div className="customer-avatar">{customer.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div><p className="eyebrow">Customer 360°</p><h1>{customer.name}</h1><p>{customer.city || "City not recorded"} · Customer since {formatDate(customer.createdAt)}</p><div className="customer-tag-row"><span className={`status-pill lifecycle-${customer.lifecycleStage}`}>{customer.lifecycleStage}</span>{customer.tags.map((tag) => <span key={tag}><Tags/>{tag}</span>)}</div></div><aside><small>Relationship owner</small><b><UserRound/>{customer.ownerUid}</b><small>Last updated {formatDate(customer.updatedAt)}</small></aside></header>
    <div className="customer-360-grid"><div className="customer-360-main"><section className="profile-panel"><header><div><span><UserRound/></span><div><h2>Contact & consent</h2><p>Verified communication details and permissions</p></div></div></header><div className="contact-grid"><div><Phone/><span>Phone</span><b>{customer.phones.join(", ")}</b></div><div><Mail/><span>Email</span><b>{customer.emails.join(", ") || "Not recorded"}</b></div><div><MapPin/><span>City</span><b>{customer.city || "Not recorded"}</b></div><div><MessageCircle/><span>Preferred channel</span><b>{customer.profile?.preferredChannel || "Not learned yet"}</b></div></div><div className="consent-row">{(["whatsapp", "email", "sms"] as const).map((channel) => <span className={customer.consent[channel] ? "allowed" : "blocked"} key={channel}>{customer.consent[channel] ? <CheckCircle2/> : <Clock3/>}{channel}: {customer.consent[channel] ? "consented" : "not consented"}</span>)}</div><p className="consent-source">Recorded via {customer.consent.source} on {formatDate(customer.consent.timestamp)}</p></section>
      <section className="profile-panel"><header><div><span><History/></span><div><h2>Travel history</h2><p>Past journeys and booking behaviour</p></div></div></header>{travelHistory.length ? <div className="travel-history">{travelHistory.map((trip) => <article key={trip.id}><div><b>{trip.destination}, {trip.country}</b><span><CalendarDays/>{formatDate(trip.dates.start)} – {formatDate(trip.dates.end)}</span></div><div><strong>₹{trip.spend.toLocaleString("en-IN")}</strong><span>{trip.travellers.type} · {trip.duration} days · {trip.purpose}</span></div></article>)}</div> : <div className="panel-empty"><History/><b>No travel history yet</b><span>Completed bookings and imported history will appear here.</span></div>}</section>
      <section className="profile-panel"><header><div><span><Clock3/></span><div><h2>Interaction timeline</h2><p>Customer activity across every connected channel</p></div></div></header>{events.length ? <ol className="event-timeline">{events.map((event) => <li key={event.id}><span></span><div><b>{event.type.replaceAll(/([A-Z])/g, " $1")}</b><p>{event.channel} · {formatDate(event.ts)}</p></div></li>)}</ol> : <div className="panel-empty"><Clock3/><b>No events captured</b><span>Enquiries, replies, bookings and campaign activity will build this timeline.</span></div>}</section></div>
      <aside className="customer-360-side"><section className="profile-panel customer-value"><header><div><span><CircleDollarSign/></span><div><h2>Customer value</h2><p>Explainable commercial signal</p></div></div></header>{customer.clv ? <><strong>{customer.clv.score}<small>/100</small></strong><span>Predicted next 12 months</span><b>₹{customer.clv.predictedNext12mo.toLocaleString("en-IN")}</b><p>{customer.clv.reasoning}</p></> : <div className="panel-empty compact"><Sparkles/><b>Still learning</b><span>CLV appears after enough booking and interaction data is available.</span></div>}</section>
      <section className="profile-panel"><header><div><span><Sparkles/></span><div><h2>Traveller intelligence</h2><p>Segments include their reasoning</p></div></div></header>{customer.segments.length ? <div className="segment-list">{customer.segments.map((segment) => <article key={segment.label}><div><b>{segment.label}</b><span>{Math.round(segment.confidence * 100)}% confidence</span></div><p>{segment.reasoning}</p></article>)}</div> : <div className="panel-empty compact"><Sparkles/><b>No segment yet</b><span>Profiles remain honest when there is not enough evidence.</span></div>}</section>
      {customer.profile && <section className="profile-panel profile-facts"><header><div><span><Sparkles/></span><div><h2>Learned preferences</h2><p>Updated {formatDate(customer.profile.computedAt)}</p></div></div></header><dl><div><dt>Total trips</dt><dd>{customer.profile.totalTrips}</dd></div><div><dt>Average spend</dt><dd>₹{customer.profile.avgSpend.toLocaleString("en-IN")}</dd></div><div><dt>Spend band</dt><dd>{customer.profile.spendBand}</dd></div><div><dt>Offer response</dt><dd>{Math.round(customer.profile.offerResponseRate * 100)}%</dd></div></dl></section>}</aside></div></>;
}
