export type AlertSeverity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type SupervisorFinding = { ruleKey: string; severity: AlertSeverity; reasoning: string; evidence: Array<{ label: string; value: string | number | boolean | null; observedAt: string }> };
export type SupervisorContext = {
  now: string; valueEstimate?: number; highValueThreshold?: number; firstResponseDueAt?: string; firstResponseAt?: string; nextFollowUpAt?: string; lastActivityAt?: string; priority?: string;
  sentimentScore?: number; previousSentimentScore?: number; repeatedQuestionCount?: number; discountPct?: number; discountLimitPct?: number; marginPct?: number; minimumMarginPct?: number;
  quotedPrice?: number; comparableMean?: number; comparableStdDev?: number; competitorPriceBetter?: boolean; clvPercentile?: number; churnScore?: number;
  paymentDueAt?: string; paymentStatus?: string; refundImpactPct?: number; responseMinutes?: number; teamMedianResponseMinutes?: number; teamStdDevResponseMinutes?: number; conversionPct?: number; teamMedianConversionPct?: number;
};
type Rule = { key: string; severity: AlertSeverity; evaluate(context: SupervisorContext): SupervisorFinding | null };
const finding = (key: string, severity: AlertSeverity, reasoning: string, label: string, value: string | number | boolean | null, now: string): SupervisorFinding => ({ ruleKey: key, severity, reasoning, evidence: [{ label, value, observedAt: now }] });
const ageHours = (now: string, then?: string) => then ? (new Date(now).getTime() - new Date(then).getTime()) / 3_600_000 : 0;

export const supervisorRules: Rule[] = [
  { key: "HIGH_VALUE_UNANSWERED", severity: "CRITICAL", evaluate: (c) => !c.firstResponseAt && Boolean(c.firstResponseDueAt) && new Date(c.now) > new Date(c.firstResponseDueAt!) && (c.valueEstimate || 0) >= (c.highValueThreshold || 150000) ? finding("HIGH_VALUE_UNANSWERED", "CRITICAL", "A high-value lead has passed its first-response SLA.", "Estimated value", c.valueEstimate || 0, c.now) : null },
  { key: "FOLLOWUP_MISSED", severity: "HIGH", evaluate: (c) => c.nextFollowUpAt && new Date(c.now) > new Date(c.nextFollowUpAt) ? finding("FOLLOWUP_MISSED", "HIGH", "The promised follow-up time has passed.", "Follow-up due", c.nextFollowUpAt, c.now) : null },
  { key: "HOT_LEAD_IGNORED", severity: "HIGH", evaluate: (c) => ["high", "urgent"].includes(c.priority || "") && ageHours(c.now, c.lastActivityAt) > 24 ? finding("HOT_LEAD_IGNORED", "HIGH", "A high-priority lead has no activity in the last 24 hours.", "Inactive hours", Math.round(ageHours(c.now, c.lastActivityAt)), c.now) : null },
  { key: "LEAD_INACTIVE_TOO_LONG", severity: "MEDIUM", evaluate: (c) => ageHours(c.now, c.lastActivityAt) > 72 ? finding("LEAD_INACTIVE_TOO_LONG", "MEDIUM", "The lead has had no recorded activity for more than three days.", "Inactive hours", Math.round(ageHours(c.now, c.lastActivityAt)), c.now) : null },
  { key: "REPEATED_QUESTION", severity: "MEDIUM", evaluate: (c) => (c.repeatedQuestionCount || 0) >= 2 ? finding("REPEATED_QUESTION", "MEDIUM", "The customer repeated a question and may need human attention.", "Repeat count", c.repeatedQuestionCount || 0, c.now) : null },
  { key: "SENTIMENT_DROP", severity: "HIGH", evaluate: (c) => c.sentimentScore !== undefined && c.previousSentimentScore !== undefined && c.sentimentScore - c.previousSentimentScore <= -.35 ? finding("SENTIMENT_DROP", "HIGH", "Customer sentiment has dropped sharply.", "Sentiment change", c.sentimentScore - c.previousSentimentScore, c.now) : null },
  { key: "CUSTOMER_DISSATISFIED", severity: "HIGH", evaluate: (c) => (c.sentimentScore ?? 0) < -.4 ? finding("CUSTOMER_DISSATISFIED", "HIGH", "Current sentiment is below the escalation threshold.", "Sentiment", c.sentimentScore ?? 0, c.now) : null },
  { key: "DISCOUNT_ABOVE_LIMIT", severity: "HIGH", evaluate: (c) => (c.discountPct || 0) > (c.discountLimitPct ?? 100) ? finding("DISCOUNT_ABOVE_LIMIT", "HIGH", "The proposed discount exceeds the permitted limit.", "Discount %", c.discountPct || 0, c.now) : null },
  { key: "MARGIN_BELOW_THRESHOLD", severity: "CRITICAL", evaluate: (c) => c.marginPct !== undefined && c.marginPct < (c.minimumMarginPct || 0) ? finding("MARGIN_BELOW_THRESHOLD", "CRITICAL", "Expected margin is below the organization minimum.", "Margin %", c.marginPct, c.now) : null },
  { key: "SUSPICIOUS_PRICE", severity: "HIGH", evaluate: (c) => c.quotedPrice !== undefined && c.comparableMean !== undefined && (c.comparableStdDev || 0) > 0 && Math.abs(c.quotedPrice - c.comparableMean) / c.comparableStdDev! >= 3 ? finding("SUSPICIOUS_PRICE", "HIGH", "The quoted price is an outlier against comparable quotes.", "Quoted price", c.quotedPrice, c.now) : null },
  { key: "COMPETITOR_PRICE_BETTER", severity: "MEDIUM", evaluate: (c) => c.competitorPriceBetter ? finding("COMPETITOR_PRICE_BETTER", "MEDIUM", "Conversation evidence indicates a competitor has a better price.", "Detected", true, c.now) : null },
  { key: "VALUABLE_CUSTOMER_AT_RISK", severity: "CRITICAL", evaluate: (c) => (c.clvPercentile || 0) >= .9 && (c.churnScore || 0) >= .6 ? finding("VALUABLE_CUSTOMER_AT_RISK", "CRITICAL", "A top-decile customer has a high churn signal.", "Churn score", c.churnScore || 0, c.now) : null },
  { key: "PAYMENT_OVERDUE", severity: "HIGH", evaluate: (c) => c.paymentStatus !== "paid" && c.paymentDueAt && new Date(c.now) > new Date(c.paymentDueAt) ? finding("PAYMENT_OVERDUE", "HIGH", "A payment remains outstanding after its due date.", "Due at", c.paymentDueAt, c.now) : null },
  { key: "REFUND_UNUSUAL_IMPACT", severity: "HIGH", evaluate: (c) => (c.refundImpactPct || 0) >= 25 ? finding("REFUND_UNUSUAL_IMPACT", "HIGH", "The refund would materially affect profitability.", "Profit impact %", c.refundImpactPct || 0, c.now) : null },
  { key: "STAFF_UNDERPERFORMING", severity: "MEDIUM", evaluate: (c) => c.responseMinutes !== undefined && c.teamMedianResponseMinutes !== undefined && c.responseMinutes > c.teamMedianResponseMinutes + (c.teamStdDevResponseMinutes || 0) && (c.conversionPct ?? 100) < (c.teamMedianConversionPct ?? 0) ? finding("STAFF_UNDERPERFORMING", "MEDIUM", "Response time and conversion are below the team baseline.", "Response minutes", c.responseMinutes, c.now) : null },
];
export function evaluateSupervisor(context: SupervisorContext) { return supervisorRules.map((rule) => rule.evaluate(context)).filter((result): result is SupervisorFinding => Boolean(result)); }
